### ISSUE TITLE
createFeatureServer() method is ambiguous

### ISSUE THREAD

**Issue by IsmaelAh** [Anwarvic/Speaker-Recognition#4]
In evaluate the model ,you call `createFeatureServer()` without argument , the implementaion in `SidekitModel` class when no parameter then:
```
feat_dir = os.path.join(self.BASE_DIR, "feat")
```
But the `feat` folder contains two folder enroll and test ,isn't i? And every one contaisn features (file.h5) , so i want to know in this case the object FeaturesServer when run, to any of features files? to enroll features files or test features files or both? And thanks

**Comment by Anwarvic** [comment]
Actually, that's a great question!!!

Look, when I was training the model, I created a feature server.. right? I created it using `server = self.createFeatureServer("enroll")`. As you can see, I have passed an argument which is `enroll`. And that's because I was passing just the training filenames -which is `train_list`- to the `EM_split()` method

In the evaluation part, I used `server = self.createFeatureServer()` without any arguments.. why is that?
Because I was passing the `test_ndx` to the `gmm_scoring()` method which contains the relative path like so `test\file.h5`. If you want to make sure, check `test_trails.txt` which was used to create `test_ndx.h5`.

I hope this answers your question and check `create_Ndx()` method in `data_init.py` script for more information.

**Comment by Anwarvic** [comment]
@IsmaelAh ... I believe this answers your question... I will close this issue but feel free to re-open it
